name: Increment Version

on: [push]

jobs:
  update-version:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Increment version
        run: |
          VERSION=$(cat version/version.txt)
          MAJOR=$(echo "$VERSION" | cut -d '.' -f 1)
          MINOR=$(echo "$VERSION" | cut -d '.' -f 2)
          PATCH=$(echo "$VERSION" | cut -d '.' -f 3)
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
          echo "$NEW_VERSION" > version/version.txt
      
      - name: Commit and push if changed
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add version/version.txt
          git commit -m "Increment version"
          git push
